ERROR:django.request:Internal Server Error: /bar/Verified_Login/
Traceback (most recent call last):
  File "C:\Users\David\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\David\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\David\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\David\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\David\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\David\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\David\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\David\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\David\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\David\3D Objects\Proyectos\Music\api\bar\views.py", line 34, in Verified_Login
    logging.info('Número que ingreso es:'+data['numer_phone'])
KeyError: 'numer_phone'
INFO:django.utils.autoreload:C:\Users\David\3D Objects\Proyectos\Music\api\bar\views.py changed, reloading.
DEBUG:asyncio:Using proactor: IocpProactor
INFO:root:Número que ingreso es:3015700795
ERROR:django.request:Internal Server Error: /bar/Verified_Login/
Traceback (most recent call last):
  File "C:\Users\David\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\David\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\David\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\David\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\Users\David\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
  File "C:\Users\David\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "C:\Users\David\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\David\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\David\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\David\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "C:\Users\David\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type BarConfigs is not JSON serializable
INFO:django.utils.autoreload:C:\Users\David\3D Objects\Proyectos\Music\api\bar\views.py changed, reloading.
DEBUG:asyncio:Using proactor: IocpProactor
INFO:root:Número que ingreso es:3015700795
INFO:root:Número que ingreso es:3015700795
INFO:django.utils.autoreload:C:\Users\David\3D Objects\Proyectos\Music\api\bar\views.py changed, reloading.
DEBUG:asyncio:Using proactor: IocpProactor
INFO:root:Número que ingreso es:3015700795
INFO:root:Número que ingreso es:3015700795
INFO:django.utils.autoreload:C:\Users\David\3D Objects\Proyectos\Music\api\bar\views.py changed, reloading.
DEBUG:asyncio:Using proactor: IocpProactor
INFO:root:Número que ingreso es:3015700795
INFO:django.utils.autoreload:C:\Users\David\3D Objects\Proyectos\Music\api\bar\views.py changed, reloading.
DEBUG:asyncio:Using proactor: IocpProactor
INFO:root:Número que ingreso es:3206538950
INFO:django.utils.autoreload:C:\Users\David\3D Objects\Proyectos\Music\api\bar\views.py changed, reloading.
DEBUG:asyncio:Using proactor: IocpProactor
INFO:root:Número que ingreso es:3206538950
INFO:django.utils.autoreload:C:\Users\David\3D Objects\Proyectos\Music\api\bar\views.py changed, reloading.
DEBUG:asyncio:Using proactor: IocpProactor
INFO:root:Número que ingreso es:1597534561
INFO:django.utils.autoreload:C:\Users\David\3D Objects\Proyectos\Music\api\bar\views.py changed, reloading.
DEBUG:asyncio:Using proactor: IocpProactor
INFO:root:Número que ingreso es:1472583690
INFO:root:Número que ingreso es:1597534560
INFO:root:Número que ingreso es:1597534561
INFO:root:Número que ingreso es:7418529630
INFO:root:Número que ingreso es:7418529630
INFO:root:Número que ingreso es:7418529630
INFO:root:Número que ingreso es:7418529630
INFO:root:Número que ingreso es:7418529630
INFO:root:Número que ingreso es:7418529630
INFO:root:Número que ingreso es:7418529630
INFO:root:Número que ingreso es:1478523690
INFO:root:Número que ingreso es:1475823690
INFO:root:Número que ingreso es:123123123
INFO:root:Número que ingreso es:1597534587
INFO:root:Número que ingreso es:2342341234
INFO:root:Número que ingreso es:1231231234
INFO:root:Número que ingreso es:1231231234
INFO:root:Número que ingreso es:789456120
INFO:django.utils.autoreload:C:\Users\David\3D Objects\Proyectos\Music\api\bar\models.py changed, reloading.
DEBUG:asyncio:Using proactor: IocpProactor
INFO:root:Número que ingreso es:1231231233
INFO:root:Número que ingreso es:1231231233
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:C:\Users\David\3D Objects\Proyectos\Music\api\bar\admin.py changed, reloading.
DEBUG:asyncio:Using proactor: IocpProactor
INFO:root:Número que ingreso es:1234567890
INFO:django.utils.autoreload:C:\Users\David\3D Objects\Proyectos\Music\api\bar\views.py changed, reloading.
DEBUG:asyncio:Using proactor: IocpProactor
INFO:root:Número que ingreso es:1235468790
INFO:root:Número que ingreso es:1231231234
INFO:root:Número que ingreso es:1231231234
